# .streamlit/secrets.toml

# .streamlit/secrets.toml

# Mercado Pago
MP_ACCESS_TOKEN = "0000003100081779202800"

# Homebanking
CBU_ALIAS = "CASINO.RED.GRITO"

# URL de tu app (para redirecciones de MP)
BASE_URL        = "https://almapaid.streamlit.app/"
